-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           8.0.18 - MySQL Community Server - GPL
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Copiando estrutura do banco de dados para rest_with_asp_net_udemy
CREATE DATABASE IF NOT EXISTS `rest_with_asp_net_udemy` /*!40100 DEFAULT CHARACTER SET utf8 */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `rest_with_asp_net_udemy`;

-- Copiando estrutura para tabela rest_with_asp_net_udemy.books
CREATE TABLE IF NOT EXISTS `books` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Author` longtext,
  `LaunchDate` datetime NOT NULL,
  `Price` decimal(65,2) NOT NULL,
  `Title` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela rest_with_asp_net_udemy.books: ~5 rows (aproximadamente)
DELETE FROM `books`;
/*!40000 ALTER TABLE `books` DISABLE KEYS */;
INSERT INTO `books` (`id`, `Author`, `LaunchDate`, `Price`, `Title`) VALUES
	(1, 'Carlos', '2020-09-24 00:00:00', 15.00, 'Livro 1'),
	(2, 'Joselito', '2020-09-24 00:00:00', 15.00, 'Livro 2'),
	(3, 'Lorannnnnnn', '2020-09-24 16:50:00', 22.00, 'Livro 3'),
	(5, 'GraziIII', '0001-01-01 00:00:00', 15.50, 'livretao'),
	(6, 'Grazi', '2020-09-24 16:50:00', 22.00, 'Livro 4');
/*!40000 ALTER TABLE `books` ENABLE KEYS */;

-- Copiando estrutura para tabela rest_with_asp_net_udemy.changelog
CREATE TABLE IF NOT EXISTS `changelog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` tinyint(4) DEFAULT NULL,
  `version` varchar(50) DEFAULT NULL,
  `description` varchar(200) NOT NULL,
  `name` varchar(300) NOT NULL,
  `checksum` varchar(32) DEFAULT NULL,
  `installed_by` varchar(100) NOT NULL,
  `installed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `success` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela rest_with_asp_net_udemy.changelog: ~6 rows (aproximadamente)
DELETE FROM `changelog`;
/*!40000 ALTER TABLE `changelog` DISABLE KEYS */;
INSERT INTO `changelog` (`id`, `type`, `version`, `description`, `name`, `checksum`, `installed_by`, `installed_on`, `success`) VALUES
	(1, 2, '0', 'Empty schema found: rest_with_asp_net_udemy.', 'rest_with_asp_net_udemy', '', 'root', '2020-09-24 21:11:39', 1),
	(2, 0, '1.0.1', 'Create Table Persons (50 ms)', 'V1_0_1__Create_Table_Persons.sql', 'CB3BD9CBD1D06445D0901B94BF218F3F', 'root', '2020-09-24 21:11:39', 1),
	(3, 0, '1.0.2', 'Alter Table Persons (69 ms)', 'V1_0_2__Alter_Table_Persons.sql', 'A1CE7BC658030AB89A97862DD8C67924', 'root', '2020-09-24 21:11:39', 1),
	(4, 0, '1.0.3', 'Create Table Books (61 ms)', 'V1_0_3__Create_Table_Books.sql', 'EBEEF2499BD01AAC5CAE8BD561E0D4CC', 'root', '2020-09-24 21:11:39', 1),
	(5, 0, '1.0.6', 'Create Table Users (6 ms)', 'V1_0_6__Create_Table_Users.sql', '194B36DB402B1C34320F7F874117BDFB', 'root', '2020-09-28 00:17:57', 0),
	(6, 0, '1.0.6', 'Create Table Users (70 ms)', 'V1_0_6__Create_Table_Users.sql', '37D3AD17F1D3EB305DB2DC94898A2D91', 'root', '2020-09-28 00:18:58', 1);
/*!40000 ALTER TABLE `changelog` ENABLE KEYS */;

-- Copiando estrutura para tabela rest_with_asp_net_udemy.logins
CREATE TABLE IF NOT EXISTS `logins` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `Logins` varchar(50) NOT NULL,
  `AccessKey` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Login` (`Logins`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela rest_with_asp_net_udemy.logins: ~0 rows (aproximadamente)
DELETE FROM `logins`;
/*!40000 ALTER TABLE `logins` DISABLE KEYS */;
INSERT INTO `logins` (`id`, `Logins`, `AccessKey`) VALUES
	(1, 'carlos', 'admin123');
/*!40000 ALTER TABLE `logins` ENABLE KEYS */;

-- Copiando estrutura para tabela rest_with_asp_net_udemy.persons
CREATE TABLE IF NOT EXISTS `persons` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `FirstName` varchar(50) DEFAULT NULL,
  `LastName` varchar(50) DEFAULT NULL,
  `Address` varchar(50) DEFAULT NULL,
  `Gender` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela rest_with_asp_net_udemy.persons: ~0 rows (aproximadamente)
DELETE FROM `persons`;
/*!40000 ALTER TABLE `persons` DISABLE KEYS */;
/*!40000 ALTER TABLE `persons` ENABLE KEYS */;

-- Copiando estrutura para tabela rest_with_asp_net_udemy.persons2
CREATE TABLE IF NOT EXISTS `persons2` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `FirstName` varchar(50) DEFAULT NULL,
  `LastName` varchar(50) DEFAULT NULL,
  `Address` varchar(50) DEFAULT NULL,
  `Gender` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=303 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- Copiando dados para a tabela rest_with_asp_net_udemy.persons2: ~0 rows (aproximadamente)
DELETE FROM `persons2`;
/*!40000 ALTER TABLE `persons2` DISABLE KEYS */;
INSERT INTO `persons2` (`ID`, `FirstName`, `LastName`, `Address`, `Gender`) VALUES
	(1, 'Joselito', 'Sem Noção', 'São Paulo - São Paulo - Brasil', 'Male'),
	(2, 'Joselito Soares', 'De Almeida', 'São Paulo - São Paulo - Brasil', 'Male'),
	(3, 'Jamison', 'Foresight', '0488 Waywood Lane', 'Male'),
	(4, 'Janine', 'Gerge', '00 Dawn Trail', 'Female'),
	(5, 'Johny', 'Sessuns', '5316 Riverside Junction', 'Male'),
	(6, 'Batholomew', 'Anstie', '7940 Starling Lane', 'Male'),
	(7, 'Algernon', 'Corbert', '5527 Green Ridge Plaza', 'Male'),
	(8, 'Janet', 'Errol', '7083 Jay Point', 'Female'),
	(9, 'Simeon', 'Locksley', '877 Brown Place', 'Male'),
	(10, 'Oates', 'Bever', '4 Kinsman Junction', 'Male'),
	(11, 'Courtney', 'Hitter', '131 Ohio Road', 'Male'),
	(12, 'Steward', 'Schimoni', '94645 Towne Circle', 'Male'),
	(13, 'Jessalin', 'Aynsley', '3 Fairfield Way', 'Female'),
	(14, 'Rois', 'Daudray', '94 Lillian Center', 'Female'),
	(15, 'Stanley', 'Vousden', '0951 Oneill Hill', 'Male'),
	(16, 'Merle', 'Stonhouse', '16001 Waywood Drive', 'Female'),
	(17, 'Briggs', 'Josef', '0352 Orin Park', 'Male'),
	(18, 'Anita', 'Beiderbecke', '40 Jenna Way', 'Female'),
	(19, 'Ichabod', 'Kauschke', '04 Myrtle Plaza', 'Male'),
	(20, 'Moss', 'O\'Ruane', '6 Shoshone Road', 'Male'),
	(21, 'Stevy', 'Ivanusyev', '9 Union Parkway', 'Male'),
	(22, 'Red', 'Streather', '23505 Londonderry Lane', 'Male'),
	(23, 'Aggy', 'Gillingham', '996 Brown Crossing', 'Female'),
	(24, 'Pattie', 'Burk', '2 Esch Street', 'Male'),
	(25, 'Darrell', 'Shera', '4 Dixon Junction', 'Male'),
	(26, 'Enoch', 'Costigan', '09268 Jenna Parkway', 'Male'),
	(27, 'Ogden', 'Hartill', '0264 Mallory Terrace', 'Male'),
	(28, 'Ban', 'Lapidus', '00 Pennsylvania Road', 'Male'),
	(29, 'Goldi', 'Withull', '8 Milwaukee Street', 'Female'),
	(30, 'Harriett', 'Luff', '5 Utah Center', 'Female'),
	(31, 'Freddy', 'd\'Escoffier', '60569 Ilene Circle', 'Female'),
	(32, 'Dolli', 'Nurdin', '6 Menomonie Lane', 'Female'),
	(33, 'Tybalt', 'Rodda', '97 Clyde Gallagher Court', 'Male'),
	(34, 'Aeriell', 'Nicklen', '29 Lakewood Way', 'Female'),
	(35, 'Juliane', 'Trask', '94328 Anzinger Crossing', 'Female'),
	(36, 'Ailina', 'Bollini', '7206 Redwing Terrace', 'Female'),
	(37, 'Blisse', 'Matuszynski', '97 Truax Point', 'Female'),
	(38, 'Jarret', 'Yearsley', '00 Anniversary Parkway', 'Male'),
	(39, 'Alphonse', 'Spellacey', '888 Anniversary Way', 'Male'),
	(40, 'Bel', 'Gounin', '81268 Ronald Regan Pass', 'Female'),
	(41, 'Ferdinanda', 'Capstaff', '2030 Corben Plaza', 'Female'),
	(42, 'Elana', 'Trusler', '44 Declaration Alley', 'Female'),
	(43, 'Vinita', 'Severns', '843 Hoffman Plaza', 'Female'),
	(44, 'Randy', 'Mattes', '98398 Warrior Circle', 'Male'),
	(45, 'Sheeree', 'Fretson', '922 Rutledge Alley', 'Female'),
	(46, 'Kelly', 'Grouen', '1517 Jenna Pass', 'Female'),
	(47, 'Seline', 'Pickance', '15 Randy Hill', 'Female'),
	(48, 'Cristian', 'Gridon', '03419 Carey Avenue', 'Male'),
	(49, 'Willy', 'Kassman', '13 Fuller Road', 'Male'),
	(50, 'Shellie', 'Duran', '09561 Weeping Birch Pass', 'Female'),
	(51, 'Abe', 'Kesten', '64 Fremont Alley', 'Male'),
	(52, 'Yetta', 'Cortez', '80 Johnson Lane', 'Female'),
	(53, 'Margarethe', 'Ruffle', '96803 Cambridge Avenue', 'Female'),
	(54, 'Costa', 'Huxstep', '144 Orin Crossing', 'Male'),
	(55, 'Ezekiel', 'Shoosmith', '01 Lerdahl Crossing', 'Male'),
	(56, 'Cairistiona', 'Passey', '33072 Southridge Lane', 'Female'),
	(57, 'Batsheva', 'Bannister', '49 Dixon Junction', 'Female'),
	(58, 'Ingeborg', 'Anselmi', '05633 Continental Road', 'Female'),
	(59, 'Bessy', 'Avramov', '859 Lawn Lane', 'Female'),
	(60, 'Amalita', 'Dragon', '054 Bonner Avenue', 'Female'),
	(61, 'Valry', 'O\' Connell', '61 Boyd Hill', 'Female'),
	(62, 'Patrizia', 'De Santos', '0 Dakota Terrace', 'Female'),
	(63, 'Rubina', 'De Witt', '6514 Harper Terrace', 'Female'),
	(64, 'Anselm', 'Janecki', '87 American Court', 'Male'),
	(65, 'Ketty', 'Mallender', '7 Loeprich Park', 'Female'),
	(66, 'Betty', 'Laws', '442 Daystar Pass', 'Female'),
	(67, 'Jacintha', 'Kitson', '4 Dottie Pass', 'Female'),
	(68, 'Teirtza', 'Girt', '20 Chive Center', 'Female'),
	(69, 'Russ', 'Pensom', '78601 Mendota Lane', 'Male'),
	(70, 'Lovell', 'Brandreth', '62569 Valley Edge Court', 'Male'),
	(71, 'Merry', 'O\' Markey', '62 Monica Crossing', 'Male'),
	(72, 'Web', 'Zaple', '86584 Jay Way', 'Male'),
	(73, 'Morena', 'Thody', '31 Towne Circle', 'Female'),
	(74, 'Cad', 'Shetliff', '8153 Evergreen Court', 'Male'),
	(75, 'Enrique', 'Martellini', '951 Bobwhite Way', 'Male'),
	(76, 'Marcie', 'Allinson', '6085 Sutteridge Terrace', 'Female'),
	(77, 'Crawford', 'Guthrum', '8099 Eliot Trail', 'Male'),
	(78, 'Nancey', 'Hatz', '2662 South Trail', 'Female'),
	(79, 'Ward', 'Ingman', '27 Victoria Street', 'Male'),
	(80, 'Judy', 'Freak', '6 Norway Maple Terrace', 'Female'),
	(81, 'Jeannine', 'Purshouse', '361 Donald Avenue', 'Female'),
	(82, 'King', 'Willcox', '454 Bonner Court', 'Male'),
	(83, 'Issie', 'Colnett', '15123 Duke Point', 'Female'),
	(84, 'Rodolphe', 'Du Plantier', '882 Towne Lane', 'Male'),
	(85, 'Michel', 'Pilbeam', '291 Gateway Lane', 'Female'),
	(86, 'Mallissa', 'Strickett', '46508 Mallard Drive', 'Female'),
	(87, 'Lonni', 'Baltrushaitis', '2 American Crossing', 'Female'),
	(88, 'Chet', 'Galsworthy', '6362 Bartelt Plaza', 'Male'),
	(89, 'Cheslie', 'Farncomb', '43 Leroy Terrace', 'Female'),
	(90, 'Philip', 'Cluelow', '38 Southridge Parkway', 'Male'),
	(91, 'Darin', 'Veysey', '3 Corscot Crossing', 'Male'),
	(92, 'Maryjane', 'McBeth', '5240 Morning Court', 'Female'),
	(93, 'Kimmie', 'Reinard', '975 Weeping Birch Street', 'Female'),
	(94, 'Erich', 'Widdows', '7828 Meadow Ridge Circle', 'Male'),
	(95, 'Yorgo', 'Sicely', '94253 Longview Junction', 'Male'),
	(96, 'Hillie', 'Kenrick', '03681 Eliot Avenue', 'Male'),
	(97, 'Milka', 'Schrader', '99720 Northfield Pass', 'Female'),
	(98, 'Cherilynn', 'Hunnaball', '9 Springs Lane', 'Female'),
	(99, 'Sarene', 'Scneider', '949 Corry Way', 'Female'),
	(100, 'Thornie', 'Puttock', '411 Eagan Road', 'Male'),
	(101, 'Erasmus', 'Dimmack', '9563 Karstens Court', 'Male'),
	(102, 'Winslow', 'Samber', '5404 Eastlawn Road', 'Male'),
	(103, 'Ebeneser', 'Jevon', '2 Hoffman Parkway', 'Male'),
	(104, 'Burty', 'Aronowitz', '58 Aberg Terrace', 'Male'),
	(105, 'Kylie', 'Lowfill', '62 Dryden Park', 'Male'),
	(106, 'Garrick', 'Feyer', '225 Waubesa Street', 'Male'),
	(107, 'Abba', 'Martugin', '498 Corry Place', 'Male'),
	(108, 'Efrem', 'Redsull', '87512 Declaration Crossing', 'Male'),
	(109, 'Roley', 'Bullcock', '90 Melby Court', 'Male'),
	(110, 'Chance', 'Cosely', '51791 Carioca Avenue', 'Male'),
	(111, 'Mendel', 'Cumberbatch', '85 Texas Plaza', 'Male'),
	(112, 'Mahmoud', 'MacCallum', '6 Monica Drive', 'Male'),
	(113, 'Edyth', 'Castelain', '8153 Anzinger Junction', 'Female'),
	(114, 'Tasha', 'Lanfear', '463 Grayhawk Point', 'Female'),
	(115, 'Elston', 'Brydell', '9 Leroy Place', 'Male'),
	(116, 'Winny', 'Leall', '5943 Bluestem Alley', 'Female'),
	(117, 'Kennie', 'Arnall', '66525 Portage Place', 'Male'),
	(118, 'Nat', 'Lovart', '34015 Redwing Pass', 'Male'),
	(119, 'Meier', 'Cliffe', '552 Hudson Parkway', 'Male'),
	(120, 'Tabbitha', 'Stoneman', '79 Schmedeman Court', 'Female'),
	(121, 'Batholomew', 'Chuck', '02 Kinsman Junction', 'Male'),
	(122, 'Albie', 'Kayne', '13 Kingsford Alley', 'Male'),
	(123, 'Garth', 'Gooderridge', '7685 Pine View Pass', 'Male'),
	(124, 'Selina', 'Muscroft', '7 Sullivan Plaza', 'Female'),
	(125, 'Glenna', 'Fuge', '7 Del Sol Hill', 'Female'),
	(126, 'Filberte', 'Chadwyck', '2 Northview Junction', 'Male'),
	(127, 'Griffith', 'Menendes', '06 Texas Trail', 'Male'),
	(128, 'Lisabeth', 'Luten', '9 Summerview Circle', 'Female'),
	(129, 'Rosita', 'Sander', '7853 Vidon Avenue', 'Female'),
	(130, 'Stacee', 'Ragdale', '8 Lyons Pass', 'Male'),
	(131, 'Farrand', 'Baptiste', '15807 Oakridge Parkway', 'Female'),
	(132, 'Reed', 'Pinniger', '8 Springs Circle', 'Male'),
	(133, 'Lemmie', 'Posnette', '95072 Everett Circle', 'Male'),
	(134, 'Arie', 'Olander', '9102 Cody Street', 'Male'),
	(135, 'Birgitta', 'Twine', '975 Ridgeview Avenue', 'Female'),
	(136, 'Knox', 'Garrie', '6 Warrior Avenue', 'Male'),
	(137, 'Terri', 'Dorracott', '152 Nevada Lane', 'Male'),
	(138, 'Vinson', 'Bangle', '39 Lotheville Crossing', 'Male'),
	(139, 'Gwenore', 'Sunderland', '32339 Merchant Crossing', 'Female'),
	(140, 'Charissa', 'Shewen', '7709 Prairie Rose Way', 'Female'),
	(141, 'Ebenezer', 'Hearst', '8869 Debra Parkway', 'Male'),
	(142, 'Muire', 'Haslam', '072 Dottie Park', 'Female'),
	(143, 'Daryl', 'Hedde', '49 Tennessee Street', 'Male'),
	(144, 'Mignon', 'Verryan', '21 Reindahl Center', 'Female'),
	(145, 'Georgiana', 'de Quincey', '0499 Roxbury Trail', 'Female'),
	(146, 'Cynthea', 'Sherwen', '51050 Logan Point', 'Female'),
	(147, 'Andris', 'Chazelas', '63 Eagan Hill', 'Male'),
	(148, 'Kyle', 'Berzon', '610 Carey Point', 'Female'),
	(149, 'Cloe', 'Glantz', '154 Muir Terrace', 'Female'),
	(150, 'Sherlocke', 'Rosencwaig', '78 Pawling Parkway', 'Male'),
	(151, 'Hali', 'Saurin', '24 Vidon Lane', 'Female'),
	(152, 'Adriena', 'Poppy', '407 Hoffman Place', 'Female'),
	(153, 'Maia', 'Proven', '958 Tennessee Terrace', 'Female'),
	(154, 'Amberly', 'Goodison', '0272 Talmadge Park', 'Female'),
	(155, 'Geneva', 'Ingleton', '3000 Portage Pass', 'Female'),
	(156, 'Charlot', 'McClenan', '0362 Coolidge Lane', 'Female'),
	(157, 'Holly', 'Bucher', '797 Bultman Drive', 'Female'),
	(158, 'Carlie', 'Lassell', '744 Hagan Way', 'Female'),
	(159, 'Libbey', 'Lovering', '8733 Eggendart Hill', 'Female'),
	(160, 'Evey', 'Hallut', '303 Petterle Plaza', 'Female'),
	(161, 'Matty', 'Van de Vlies', '5 Towne Plaza', 'Female'),
	(162, 'Alla', 'Dockrell', '34 Scott Pass', 'Female'),
	(163, 'Galven', 'Shortall', '8 Annamark Alley', 'Male'),
	(164, 'Marsha', 'Meatcher', '080 Mayfield Plaza', 'Female'),
	(165, 'Steffen', 'Derham', '317 Lakeland Alley', 'Male'),
	(166, 'Emalee', 'Portigall', '39 Dennis Way', 'Female'),
	(167, 'Harvey', 'Kyte', '16 7th Street', 'Male'),
	(168, 'Jens', 'Sherry', '69645 Leroy Alley', 'Male'),
	(169, 'Francesco', 'Smaridge', '83764 Forster Road', 'Male'),
	(170, 'Evangeline', 'Loble', '01172 Bartillon Lane', 'Female'),
	(171, 'Cristiano', 'Hawarden', '43 8th Lane', 'Male'),
	(172, 'Alexandre', 'Peinke', '06255 Duke Pass', 'Male'),
	(173, 'Travers', 'Beinke', '53853 Bonner Center', 'Male'),
	(174, 'Alexander', 'Hatherall', '3 Sunnyside Parkway', 'Male'),
	(175, 'Chloris', 'Muglestone', '77584 Oak Hill', 'Female'),
	(176, 'Kellen', 'Creber', '4 Briar Crest Court', 'Female'),
	(177, 'Wilhelmina', 'Sawkins', '97 Iowa Road', 'Female'),
	(178, 'Cordie', 'Tiffin', '58638 Vahlen Center', 'Female'),
	(179, 'Claudia', 'Wye', '8947 Bluestem Crossing', 'Female'),
	(180, 'Emilee', 'Ingledow', '2711 Sommers Crossing', 'Female'),
	(181, 'Aloin', 'Mc Gorley', '8 Pawling Court', 'Male'),
	(182, 'Worth', 'Colson', '58 Dwight Park', 'Male'),
	(183, 'Ninon', 'Bortoloni', '07746 Packers Trail', 'Female'),
	(184, 'Lauralee', 'Le Guin', '1875 Mifflin Avenue', 'Female'),
	(185, 'Worth', 'Hub', '9115 Helena Point', 'Male'),
	(186, 'Pandora', 'Vears', '9 Scott Crossing', 'Female'),
	(187, 'Karisa', 'Waterhouse', '6161 Esch Center', 'Female'),
	(188, 'Hashim', 'Coche', '0 Merchant Avenue', 'Male'),
	(189, 'Gerda', 'Oswick', '6030 Warrior Point', 'Female'),
	(190, 'Orland', 'Brockman', '75 Del Mar Court', 'Male'),
	(191, 'Tracy', 'Mallan', '1850 Kedzie Terrace', 'Male'),
	(192, 'Stacy', 'Prestage', '740 Veith Crossing', 'Male'),
	(193, 'Jillene', 'Gerram', '47 Dakota Hill', 'Female'),
	(194, 'Eduino', 'Scragg', '3 International Plaza', 'Male'),
	(195, 'Jillane', 'Wayte', '20039 Novick Alley', 'Female'),
	(196, 'Esther', 'Walding', '722 Elka Lane', 'Female'),
	(197, 'Dolph', 'Ainsbury', '8147 Declaration Terrace', 'Male'),
	(198, 'Roderigo', 'Wilkerson', '09 Orin Trail', 'Male'),
	(199, 'Amara', 'Riveles', '460 Lyons Road', 'Female'),
	(200, 'Eal', 'Skeete', '2 Nevada Plaza', 'Male'),
	(201, 'Leia', 'Broadnicke', '02931 Delaware Lane', 'Female'),
	(202, 'Rhody', 'Squibe', '0815 Ridge Oak Terrace', 'Female'),
	(203, 'Henry', 'Geck', '4 Victoria Junction', 'Male'),
	(204, 'Sayre', 'Uttley', '93293 Pankratz Crossing', 'Female'),
	(205, 'Freida', 'Hellwig', '234 Center Park', 'Female'),
	(206, 'Bev', 'McKern', '57409 Jackson Road', 'Male'),
	(207, 'Gladys', 'Arrol', '74 Pearson Street', 'Female'),
	(208, 'Codie', 'Everix', '8 Fieldstone Road', 'Female'),
	(209, 'Delphinia', 'Oughton', '6755 Butternut Point', 'Female'),
	(210, 'Allys', 'Fisby', '99 Farmco Terrace', 'Female'),
	(211, 'Jerri', 'McElrea', '38 Novick Trail', 'Male'),
	(212, 'Tabbie', 'Monckton', '784 Longview Lane', 'Male'),
	(213, 'Mose', 'Newiss', '191 Helena Park', 'Male'),
	(214, 'Sandie', 'Splevin', '2271 Hooker Trail', 'Female'),
	(215, 'Winnie', 'Betser', '1 Birchwood Place', 'Female'),
	(216, 'Hally', 'Moreing', '5 Crowley Parkway', 'Female'),
	(217, 'Malvin', 'Overton', '13 Hansons Avenue', 'Male'),
	(218, 'Sherm', 'Mahon', '2266 Bunker Hill Alley', 'Male'),
	(219, 'Milt', 'Andrivel', '555 Susan Lane', 'Male'),
	(220, 'Frans', 'Bertelsen', '0249 Muir Plaza', 'Male'),
	(221, 'Roberta', 'Van der Krui', '202 Almo Trail', 'Female'),
	(222, 'Wynnie', 'Harfleet', '01813 Saint Paul Parkway', 'Female'),
	(223, 'Kristofer', 'Brahams', '4 Lindbergh Way', 'Male'),
	(224, 'Zoe', 'Dreghorn', '964 Eastwood Avenue', 'Female'),
	(225, 'Monti', 'Wind', '22681 Weeping Birch Street', 'Male'),
	(226, 'Hazlett', 'Dubock', '0610 Mayer Lane', 'Male'),
	(227, 'Chrysa', 'McCrackem', '8436 Kingsford Place', 'Female'),
	(228, 'Tiebout', 'Hugnin', '1063 Granby Road', 'Male'),
	(229, 'Jayson', 'Turbill', '3 Melby Point', 'Male'),
	(230, 'Katherine', 'O\' Markey', '90898 Red Cloud Place', 'Female'),
	(231, 'Whittaker', 'Dulanty', '42776 Havey Road', 'Male'),
	(232, 'Illa', 'Ballchin', '83 Melby Plaza', 'Female'),
	(233, 'Flora', 'Gillatt', '232 Hazelcrest Place', 'Female'),
	(234, 'Tull', 'Sandwick', '72259 Oriole Avenue', 'Male'),
	(235, 'Skippie', 'Beverley', '9 Huxley Center', 'Male'),
	(236, 'Wyatan', 'Cressar', '45 Victoria Road', 'Male'),
	(237, 'Ardenia', 'Deelay', '54516 Lien Parkway', 'Female'),
	(238, 'Berkley', 'Joliffe', '3 Forest Dale Place', 'Male'),
	(239, 'Michal', 'McKintosh', '3 Meadow Vale Parkway', 'Female'),
	(240, 'Ariel', 'Killeley', '780 Mayfield Terrace', 'Male'),
	(241, 'Hadleigh', 'Overnell', '4 Coleman Pass', 'Male'),
	(242, 'Murdoch', 'Heaysman', '07 Redwing Alley', 'Male'),
	(243, 'Anatola', 'Scutcheon', '94633 Kingsford Avenue', 'Female'),
	(244, 'Rea', 'Pinnijar', '93423 Dwight Way', 'Female'),
	(245, 'Nita', 'Fitzer', '532 Starling Circle', 'Female'),
	(246, 'Gibb', 'Alcott', '9259 Debs Junction', 'Male'),
	(247, 'Corty', 'Tilson', '55908 Pepper Wood Junction', 'Male'),
	(248, 'Malchy', 'Gwyneth', '237 David Court', 'Male'),
	(249, 'Andrea', 'Belcham', '406 Milwaukee Alley', 'Female'),
	(250, 'Ezechiel', 'Cribbott', '105 Summer Ridge Park', 'Male'),
	(251, 'Emily', 'Rawdales', '8 Basil Pass', 'Female'),
	(252, 'Godwin', 'Dunston', '31429 Northwestern Point', 'Male'),
	(253, 'Arly', 'Shimony', '532 Crowley Avenue', 'Female'),
	(254, 'Nikolaos', 'Shinn', '77063 Bluejay Junction', 'Male'),
	(255, 'Ali', 'Thornewell', '245 Fairview Road', 'Female'),
	(256, 'Franny', 'Kitt', '5484 Erie Pass', 'Female'),
	(257, 'Dagmar', 'Dory', '4295 Thackeray Road', 'Female'),
	(258, 'Cathrin', 'MacAlpine', '1 Nobel Court', 'Female'),
	(259, 'Dukey', 'Rossbrook', '106 Tomscot Avenue', 'Male'),
	(260, 'Reinhold', 'Broadhead', '2 Dayton Hill', 'Male'),
	(261, 'Ronny', 'Lobell', '8494 Mandrake Hill', 'Male'),
	(262, 'Garfield', 'Linklater', '7736 Rusk Point', 'Male'),
	(263, 'Benny', 'Cocher', '86 2nd Street', 'Female'),
	(264, 'Godfry', 'Peppard', '0537 Butterfield Circle', 'Male'),
	(265, 'Stephenie', 'Crumly', '8 Sunfield Parkway', 'Female'),
	(266, 'Bridgette', 'Vinecombe', '56856 Daystar Place', 'Female'),
	(267, 'Farra', 'Spitaro', '3 Mcguire Place', 'Female'),
	(268, 'Rhys', 'Francino', '11442 Debs Circle', 'Male'),
	(269, 'Lea', 'Brum', '9 Manley Lane', 'Female'),
	(270, 'Hinze', 'Van Waadenburg', '0 Ohio Alley', 'Male'),
	(271, 'Reginald', 'Anstead', '35 Londonderry Plaza', 'Male'),
	(272, 'Maggi', 'Plail', '67602 Harbort Crossing', 'Female'),
	(273, 'Westleigh', 'Shakesby', '1 Service Road', 'Male'),
	(274, 'Orazio', 'Eskrigge', '1871 Oriole Court', 'Male'),
	(275, 'Katti', 'Rivard', '668 Forster Avenue', 'Female'),
	(276, 'Gwenore', 'Quickenden', '3 Merry Street', 'Female'),
	(277, 'Dulce', 'Ritzman', '16313 Morningstar Lane', 'Female'),
	(278, 'Kristine', 'Gronav', '4 Mandrake Crossing', 'Female'),
	(279, 'Forest', 'Fildes', '3 Welch Hill', 'Male'),
	(280, 'Seumas', 'Jojic', '34 Gale Alley', 'Male'),
	(281, 'Barty', 'Chesser', '63 Esker Hill', 'Male'),
	(282, 'Demetrius', 'Savin', '64 Melvin Alley', 'Male'),
	(283, 'Launce', 'Braund', '6542 Darwin Street', 'Male'),
	(284, 'Donall', 'Rimmington', '0286 Rowland Place', 'Male'),
	(285, 'Mitchael', 'Blessed', '3 Hovde Street', 'Male'),
	(286, 'Conant', 'Elkington', '567 Arizona Place', 'Male'),
	(287, 'Farleigh', 'Thoresby', '016 Cottonwood Center', 'Male'),
	(288, 'Syd', 'Vise', '22648 Transport Junction', 'Male'),
	(289, 'Romy', 'Eberlein', '03 Sutherland Drive', 'Female'),
	(290, 'Helena', 'Ible', '33447 Logan Circle', 'Female'),
	(291, 'Darcey', 'Worgan', '1 Hermina Junction', 'Female'),
	(292, 'Milicent', 'Kendle', '2232 Gale Road', 'Female'),
	(293, 'Katrinka', 'Groocock', '96 Melody Drive', 'Female'),
	(294, 'Vito', 'Stouther', '68598 Mayer Hill', 'Male'),
	(295, 'Annemarie', 'Parcell', '62 Rowland Avenue', 'Female'),
	(296, 'Karee', 'Callam', '4 Derek Alley', 'Female'),
	(297, 'Allina', 'Dake', '90 Beilfuss Pass', 'Female'),
	(298, 'Aleece', 'Barnewille', '23234 Magdeline Court', 'Female'),
	(299, 'Nikita', 'Steptowe', '22984 Gina Court', 'Male'),
	(300, 'Breanne', 'Sarah', '60 Cascade Street', 'Female'),
	(301, 'Thomasina', 'O\'Cannavan', '05 Grayhawk Way', 'Female'),
	(302, 'Clerc', 'Jenne', '47 Fisk Way', 'Male');
/*!40000 ALTER TABLE `persons2` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
